[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
# Check https://python-poetry.org/docs/pyproject/ for all available sections
name = "pytwin"
version = "0.2.dev0"
description = "A python wrapper for Ansys Digital Twin components"
license = "MIT"
authors = ["ANSYS, Inc. <ansys.support@ansys.com>"]
maintainers = ["PyAnsys developers <pyansys.maintainers@ansys.com>"]
readme = "README.rst"
repository = "https://github.com/pyansys/pytwin"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
packages = [
    { include = "pytwin" },
]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
importlib-metadata = {version = "^4.0", python = "<3.8"}
pytest = "7.1.2"
numpy = "1.23.1"
pandas = "1.4.3"
matplotlib = "^3.6.0"
fluent = "^0.10.0"
ansys-fluent-core = "^0.11.0"
pyvista = "^0.36.1"
ansys-mapdl-core = "^0.63.3"
pywin32 = "*"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
force_sort_within_sections = true
line_length = 100
default_section = "THIRDPARTY"
src_paths = ["doc", "pytwin", "tests"]

[tool.coverage.run]
source = ["pytwin"]

[tool.coverage.report]
show_missing = true
